In [7]:
import numpy as np

A = np.array([
    [1,2,1],
    [0,1,3],
    [2,-1,-12]
    ])

A_inv = np.linalg.inv(A)

print(f"역행렬:\n {A_inv}")
print("검증(A@A_inv):\n", A@A_inv)


역행렬:
 [[ -9.  23.   5.]
 [  6. -14.  -3.]
 [ -2.   5.   1.]]
검증(A@A_inv):
 [[ 1.00000000e+00 -3.55271368e-15 -2.22044605e-16]
 [-4.44089210e-16  1.00000000e+00  2.22044605e-16]
 [ 1.77635684e-15  0.00000000e+00  1.00000000e+00]]
